config/routes.rb
Rails.application.routes.draw do
	
  root 'home_pages#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get "/history", to: "histories#index"
  get '404', to:'public#404'
  
  devise_for :users
  resources :tours
  resources :users, only: :show
  resources :bookings
  resources :reviews
   resources :comments

  namespace :admin do
    root "dashboard#index"
    resources :categories
    resources :users
    resources :comments
    resources :bookings
    resources :tours do
      resources :description_details, except: %i(index show)
    end
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :category
  has_many :description_details
  has_many :reviews

  mount_uploader :image, ImageUploader

  validate :image_size

  scope :tours_international, ->(category_id){where category_id: category_id}
  scope :tours_domestic, ->(category_id){where category_id: category_id}
  scope :available, ->{where deleted_at: false}

  private

  def image_size
    return errors.add :image, "Loi hinh anh" if image.size > 5.megabytes
  end
end

app/controllers/admin/tours_controller.rb
module Admin
	class Admin::ToursController < BaseController
		before_action :load_tour, except: %i(index new create)
		before_action :load_categories

		def index
			 @admin_tours = Tour.available.paginate(page: params[:page], per_page: 10)
		end

		def show
    		 @admin_descripption_details = DescriptionDetail.hidden_expired_detail.desription_detail_by_tour @admin_tour
  		end

		def new
    		@admin_tour = Tour.new
  		end

  		def create
	    	@admin_tour = Tour.new(admin_tour)
		    if @admin_tour.save
		      flash[:success] = "them tour thanh cong"
		      redirect_to admin_tours_path
		    else
		      render 'new'
		    end
	  	end

	  	def edit; end

		def update
		    @admin_tour = Tour.find(params[:id])
		    if @admin_tour.update_attributes(admin_tour)
		      flash[:success] = "da chinh sua thanh cong"
      		  redirect_to admin_tours_path
		    else
		      render 'edit'
		    end
		 end

	  	def destroy
		    @admin_tour.toggle! :deleted_at
		    flash[:success] = "xoa tour thanh cong"
		    redirect_to admin_tours_path
		end

	  	private

		    def admin_tour
		      params.require(:tour).permit(:name, :category_id, :content, :image, :deleted_at)
		    end

		    def load_categories
		      @categories = Category.all
		    end

		    def load_tour
		      @admin_tour = Tour.available.find_by id: params[:id]
		      return if @admin_tour
		      flash[:danger] = "khong co tour can tim"
		      redirect_to admin_tours_url
		  	end
	end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :load_tour, only: :show

  def index 
    @search = Tour.available.search params[:q]
    if params[:filter] == "tours_domestic"
      @tours = Tour.available.tours_domestic(1)
    elsif params[:filter] == "tours_international" 
      @tours = Tour.available.tours_international(2)
    else
      @tours = @search.result(distinct: true)
      .paginate(page: params[:page], per_page: 10)
    end
  end

  def show 
    @review = Review.new
    @comment = Comment.new
    @reviews = @tour.reviews.order(id: :desc).paginate(page: params[:page], per_page: 5)
    @comments = @review.comments
	  @descripption_details = DescriptionDetail.hidden_expired_detail.desription_detail_by_tour @tour
	  @tours_domestic = Tour.tours_domestic(1).sample(4)
    @tours_international = Tour.tours_international(2).sample(4)
  end

  private

  def load_tour
    @tour = Tour.available.find_by id: params[:id]
    return if @tour
    flash[:danger] = "error"
    redirect_to root_url
  end
end

app/helpers/admin/tours_helper.rb
module Admin::ToursHelper
end

app/views/admin/tours/edit.html.erb
<% provide(:title, "Chỉnh Sữa tour")%>
<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Chinh Sua Tour</h4>
                </div>
                <div class="card-body">
                  <%= form_for [:admin, @admin_tour] do |f| %>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <%= f.label :name, class: 'bmd-label-floating'%>
                          <%= f.text_field :name, class: 'form-control' %>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <%= f.label :category, "Danh Muc", class: "bmd-label-floating" %>
                          <%= f.select(:category_id, options_for_select(@categories.collect{|c| [c.name, c.id]}), {}, { class: "form-control" }) %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <%= f.label :image, "Hình Ảnh", class: "col-md-2 control-label" %>
                        <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png", class: "form-control-file", id: "exampleInputFile" %> 
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label :content%>
                          <%= f.text_field :content, class: 'form-control'%>
                          
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-5"></div>
                      <div class="col-md-4">
                        <button type="submit" class="btn btn-primary text-center">Chỉnh Sữa</button>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
</div>   

app/views/admin/tours/index.html.erb
<% provide(:title, "Quản Lý Tour")%>
<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <%= link_to "Thêm mới", new_admin_tour_path, class: "btn btn-warning" %>
              <div class="card">
                <div class="card-header card-header-primary" >
                  <h4 class="card-title ">Tour Trong Nước</h4>
                </div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table">
                        <thead class=" text-primary text-center">
                          <th>ID</th>
                          <th>Tên Loại Tour</th>
                          <th>Tên Tour</th>
                          <th>Hình Ảnh</th>
                          <th class="ct" >Nội Dung</th>
                          <th>Chức Năng</th>
                        </thead>
                        <tbody>
                          <% flash.each do |message_type, message| %>
                            <div class="message alert alert-<%= message_type %>"><%= message %></div>
                          <% end %>
                          <% @admin_tours.each do |admin_tour| %>
                          <tr class="text-center">
                            <td><%= admin_tour.id %></td>
                            <td><%= admin_tour.category.name %></a></td>
                            <td><%= link_to admin_tour.name, admin_tour_path(admin_tour) %></td>
                            <td>
                              <%=  image_tag admin_tour.image.thumb.url if admin_tour.image? %>
                            </td>
                            <td class="ct" id="nd">
                            <%= admin_tour.content %>        
                            </td>
                            <td>
                              <%= link_to "Sửa", edit_admin_tour_path(admin_tour) %>
                              <%= image_tag("edit.png", class: 'image_edit_delete')%>
                              <%= link_to admin_tour_path(admin_tour), method: :delete,data: { confirm: "ban muon xoa binh luan?" } do %>
                              Delete
                              <%= image_tag("delete.png", class: 'image_edit_delete') %>
                        <% end %>
                            </td>
                          </tr>   
                          <% end %>                                                                       
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <%= will_paginate @admin_tours %>
            </div>
        </div>
  </div>
</div>

app/views/admin/tours/new.html.erb
<% provide(:title, "Thêm Mới tour")%>
<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Thêm Tour</h4>
                </div>
                <div class="card-body">
                   <%= form_for [:admin, @admin_tour] do |f| %>
                    <%= hidden_field_tag "tour[deleted_at]", 0 %>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <%= f.label :name, class: 'bmd-label-floating'%>
                          <%= f.text_field :name, class: 'form-control' %>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <%= f.label :category, "Danh Muc", class: "bmd-label-floating" %>
                              <%= f.select(:category_id, options_for_select(@categories.collect{|c| [c.name, c.id]}), {}, { class: "form-control" }) %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <%= f.label :image, "Hình Ảnh", class: "col-md-2 control-label" %>
                        <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png", class: "form-control-file", id: "exampleInputFile" %>                                            
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label :content%>
                          <%= f.text_area :content, class: 'form-control'%>
                          
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-5"></div>
                      <div class="col-md-4">
                        <button type="submit" class="btn btn-primary text-center">Thêm Mới</button>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
</div>   

app/views/admin/tours/show.html.erb
<% provide(:title, "Thông Tin Chi Tiết Tour")%>

  <div class="chitietAdmin">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-1">                      
                </div>
                <div id="chitietTour" class="col-sm-6">
                        <h2 id="titleTT" class="text-center"><%= @admin_tour.name %></h2>
                       <p id="noidung"><%= @admin_tour.content %></p>
                </div>
                <div class="col-sm-1"></div>
                <div class="col-sm-3">                                               
                    <div id="themT" class="text-center" > 
                      <%= link_to new_admin_tour_description_detail_path(@admin_tour), id: 'addTour' do %> 
                        <i class="fa fa-plus-square" aria-hidden="true"></i> Thêm
                      <% end %>                                    
                    </div>             
                    <% @admin_descripption_details.each do |admin_descripption_detail| %>            
                      <div id="checkTour"  >
                          <div id="checkAdmin"> 
                                <p><span class="fa fa-calendar-check-o"></span><strong> Ngày Khởi Hành : </strong> 
                                  <%= l admin_descripption_detail.start_day, format: "%d-%m-%Y" %></p>
                                <p><span class="fa fa-calendar-times-o"></span><strong> Ngày Kết Thúc : </strong> <%= l admin_descripption_detail.end_day, format: "%d-%m-%Y" %></p>
                                <p><span class="fa fa-address-book-o"></span><strong> Số Chổ Còn Trống
                                 : </strong> 
                                 <%= admin_descripption_detail.max_quantity%> </p>
                                <h3 class="text-center"><%= admin_descripption_detail.price %> USD</h3>        
                          </div>
                          <div class="text-center">
                            <%= link_to edit_admin_tour_description_detail_path(@admin_tour, admin_descripption_detail), id: 'editTour' do %> 
                              <i class="fa fa-pencil" aria-hidden="true"> </i> Sửa
                              <% end %>
                              <%= link_to admin_tour_description_detail_path(@admin_tour, admin_descripption_detail), id: 'xoaTour', method: :delete,data: { confirm: "ban muon xoa binh luan?" } do %> 
                              <i class="fa fa-trash-o" aria-hidden="true"> </i> xoa
                              <% end %>
                                   
                          </div> 
                      </div>  
                    <% end %>                 
                </div>
                <div class="col-sm-1"></div>
            </div>
        </div>
  </div>