config/routes.rb
Rails.application.routes.draw do
	
  root 'home_pages#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get "/history", to: "histories#index"
  get '404', to:'public#404'
  
  devise_for :users
  resources :tours
  resources :users, only: :show
  resources :bookings
  resources :reviews
   resources :comments

  namespace :admin do
    root "dashboard#index"
    resources :categories
    resources :users
    resources :comments
    resources :bookings
    resources :tours do
      resources :description_details, except: %i(index show)
    end
  end
end

app/views/admin/share/_sidebar.html.erb
<div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
      <div class="logo text-center">
        <%= link_to image_tag('logo.png'), root_path, class: "navbar-brand" %>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item ">
            <%= link_to admin_root_path, class: "nav-link" do %>
              <i class="fa fa-home" aria-hidden="true"></i>
              <p>Trang chủ</p>
            <% end %>
          </li>
          <li class="nav-item ">
            <%= link_to admin_categories_path, class: "nav-link" do %>
              <i class="fa fa-list-alt" aria-hidden="true"></i>
              <p>Quan Lý Danh Mục</p>
            <% end %>
          </li>
          <li class="nav-item ">
            <%= link_to admin_tours_path, class: "nav-link" do %>
              <i class="fa fa-plane" aria-hidden="true"></i>
              <p>Tour</p>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_bookings_path, class: "nav-link" do %>
              <i class="fa fa-money" aria-hidden="true"></i>
              <p>Booking</p>
            <% end %>
           
          </li>
          <li class="nav-item ">
            <%= link_to admin_comments_path, class: "nav-link" do %>
              <i class="fa fa-commenting" aria-hidden="true"></i>
              <p>Bình Luận</p>
            <% end %>
          </li>
          <% if current_user.admin? %>
          <li class="nav-item ">
            <%= link_to admin_users_path, class: "nav-link" do %>
              <i class="fa fa-user" aria-hidden="true"></i>
              <p>Thông Tin Người Dùng</p>
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">          
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="fa fa-search" aria-hidden="true"></i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-user" aria-hidden="true"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                  <%= link_to "Thông Tin", current_user, class: "dropdown-item"%>
                  <div class="dropdown-divider"></div>
                  <%= link_to "Log out", destroy_user_session_path , class: 'dropdown-item', method: :delete  %>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>