config/routes.rb
Rails.application.routes.draw do
	
  root 'home_pages#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get "/history", to: "histories#index"
  get '404', to:'public#404'
  
  devise_for :users
  resources :tours
  resources :users, only: :show
  resources :bookings
  resources :reviews
   resources :comments

  namespace :admin do
    root "dashboard#index"
    resources :categories
    resources :users
    resources :comments
    resources :bookings
    resources :tours do
      resources :description_details, except: %i(index show)
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :tours
end

app/controllers/admin/categories_controller.rb
module Admin
	class CategoriesController < BaseController
		def index
			@admin_categories = Category.all.paginate(page: params[:page], per_page: 5)
		end
		 		 
  		def new
    		@admin_category = Category.new
  		end

  		def create
	    	@admin_category = Category.new(admin_category)
		    if @admin_category.save
		      redirect_to admin_categories_path
		    else
		      render 'new'
		    end
	  	end

	  	def edit
		    @admin_category = Category.find(params[:id])
		end

		def update
		    @admin_category = Category.find(params[:id])
		    if @admin_category.update_attributes(admin_category)
		      flash[:success] = "da chinh sua"
      		  redirect_to admin_categories_path
		    else
		      render 'edit'
		    end
		 end


	  	def destroy
		    Category.find_by(id: params[:id]).destroy
		    flash[:success] = "xoa danh muc"
		    redirect_to admin_categories_path
		 end

	  	private

		    def admin_category
		      params.require(:category).permit(:name)
		    end

			
		   


	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<% provide(:title, "Chỉnh Sữa Danh Mục")%>
<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">chinh sua Danh Mục</h4>
                </div>
                <div class="card-body">
                    <%= form_for [:admin, @admin_category] do |f| %>
                    <div class="row">
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label :name, class: 'bmd-label-floating'%>
                          <%= f.text_field :name, class: 'form-control' %>
                        </div>
                      </div>
                    </div>                    
                    <div class="row">
                      <div class="col-md-4"></div>
                      <div class="col-md-4">
                        <%= f.submit "Chỉnh Sữa", class: "btn btn-primary text-center",data: { confirm: "ban co muon chinh sua danh muc " } %>
                      </div>
                    </div>
                    <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
</div>    

app/views/admin/categories/index.html.erb
<% provide(:title, "Quản Lý Danh Mục")%>
<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
               <%= link_to "them moi", new_admin_category_path, class: "btn btn-warning" %>
              <div class="card">
                <div class="card-header card-header-primary" >
                  <h4 class="card-title ">Quản Lý Danh Mục</h4>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary text-center">
                        <th>ID</th>
                        <th>Tên Loại Tour</th>
                        <th>Chức Năng</th>
                      </thead>
                      <tbody>
                         <% flash.each do |message_type, message| %>
                            <div class="message alert alert-<%= message_type %>"><%= message %></div>
                          <% end %>
                        <% @admin_categories.each do |admin_category | %>
                          <tr class="text-center">
                            <td><%= admin_category.id %></td>
                            <td><%= admin_category.name %></td>
                            <td>
                              <%= link_to "Sửa", edit_admin_category_path(admin_category) %>
                              <%= image_tag("edit.png", class: 'image_edit_delete') %>
                              <% if current_user.admin? %>
                                <%= link_to admin_category_path(admin_category), method: :delete,data: { confirm: "You sure?" } do %>
                                    Delete
                                    <%= image_tag("delete.png", class: 'image_edit_delete') %>
                                <% end %>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>     
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          <%= will_paginate @admin_categories %>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<% provide(:title, "Thêm Mới Danh Mục")%>
<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Thêm Danh Mục</h4>
                </div>
                <div class="card-body">
                    <%= form_for [:admin, @admin_category] do |f| %>
                    <div class="row">
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label :name, class: 'bmd-label-floating'%>
                          <%= f.text_field :name, class: 'form-control' %>
                        </div>
                      </div>
                    </div>                    
                    <div class="row">
                      <div class="col-md-4"></div>
                      <div class="col-md-4">
                        <%= f.submit "Thêm Mới", class: "btn btn-primary text-center",data: { confirm: "ban muon them danh muc" } %>
                      </div>
                    </div>
                    <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
</div>    