config/routes.rb
Rails.application.routes.draw do
	
  root 'home_pages#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get "/history", to: "histories#index"
  get '404', to:'public#404'
  
  devise_for :users
  resources :tours
  resources :users, only: :show
  resources :bookings
  resources :reviews
   resources :comments

  namespace :admin do
    root "dashboard#index"
    resources :categories
    resources :users
    resources :comments
    resources :bookings
    resources :tours do
      resources :description_details, except: %i(index show)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
 # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable

  has_many :bookings
  has_many :reviews

  # has_secure_password

  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true, on: :create

  enum role: {admin: 1, customer: 0, staff: 2}
end

app/controllers/admin/users_controller.rb
module Admin
	class UsersController < BaseController
		def index
		  @admin_users = User.all.paginate(page: params[:page], per_page: 10)
		  if !current_user.admin?
			redirect_to admin_root_path
		  end
		end
		 	

		def new
    	  @admin_user = User.new
  		end

  		def create
	      @admin_user = User.new(admin_user)
		  if @admin_user.save
		    flash[:success] = "them thanh cong"
		    redirect_to admin_users_path
		  else
		    render 'new'
		  end
	  	end

	  	def edit
		  @admin_user = User.find(params[:id])
		end

		def update
	      @admin_user = User.find(params[:id])
	      if @admin_user.update_attributes(admin_user)
	        flash[:success] = "da chinh sua thanh cong"
  		    redirect_to admin_users_path
	      else
	        flash[:danger] = "chinh sua that bai"
	        render 'edit'
	      end
		end

	  	def destroy
	      User.find_by(id: params[:id]).destroy
	      flash[:success] = "xoa nguoi dung thanh cong"
	      redirect_to admin_users_path
		end


	  	private

	    def admin_user
	      params.require(:user).permit(:name, :email, :password, :password_confirmation, :address, :phone_number, :role)
	    end
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :logged_in_user, only: [:index, :edit, :update]
  # before_action :correct_user,   only: [:index, :edit, :update]
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  # def new
  #   @user = User.new
  # end

  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     log_in @user
  #     flash[:success] = "Welcome to viet travel"
  #     redirect_to current_user
  #   else
  #     flash.now[:danger] = 'Invalid email/password combination'
  #     render 'new'
  #   end
  # end

  # def edit
  #   @user = User.find(params[:id])
  # end

  # def update
  #   @user = User.find(params[:id])
  #   if @user.update_attributes(user_params)
  #     redirect_to current_user
  #   else
  #     render "edit"
  #   end
  # end

  private

    def user_params
      params.require(:user).permit(:name, :email,:password, :password_confirmation, :address, :phone_number)
    end

    def logged_in_user
      unless user_signed_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless @user == current_user
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<% provide(:title, "Chỉnh Sữa Người Dùng")%>
<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Chinh Sua Người Dùng</h4>
                </div>
                <div class="card-body">
                  <% flash.each do |message_type, message| %>
                            <div class="message alert alert-<%= message_type %>"><%= message %></div>
                          <% end %>
                   <%= form_for [:admin, @admin_user] do |f| %>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <%= f.label :name, class: 'bmd-label-floating'%>
                          <%= f.text_field :name, class: 'form-control' %>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <%= f.label :email, class: 'bmd-label-floating'%>
                          <%= f.email_field :email, class: 'form-control', readonly: "False" %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label :password, class: 'bmd-label-floating' %>
                          <%= f.password_field :password, class: 'form-control'%>
                        </div>
                      </div>
                    </div>
                     <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label :password_confirmation, class: 'bmd-label-floating' %>
                          <%= f.password_field :password_confirmation, class: 'form-control' %>
                        </div>
                      </div>
                    </div> 
                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                          <%= f.label :address, class: 'bmd-label-floating'%>
                          <%= f.text_field :address, class: 'form-control' %>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :phone_number, class: 'bmd-label-floating'%>
                          <%= f.text_field :phone_number, class: 'form-control' %>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <%= f.label :role, "Cấp Bậc", class: "bmd-label-floating" %>
                          <%= f.select(:role, options_for_select(User.roles.map{|key, val| [key.humanize, key]}), {}, { class: "form-control" }) %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-5"></div>
                      <div class="col-md-4">
                          <%= f.submit "Chỉnh Sữa", class: "btn btn-primary text-center" %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
</div>   

app/views/admin/users/index.html.erb
<% provide(:title, "Quản Lý Thông Tin Người Dùng")%>
 <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
            		<%= link_to "Thêm mới", new_admin_user_path, class: "btn btn-warning" %>
              <div class="card">
                <div class="card-header card-header-primary" >
                  <h4 class="card-title ">Thông Tin Người Dùng</h4>
                </div>
                <% flash.each do |message_type, message| %>
                  <div class="message alert alert-<%= message_type %>"><%= message %></div>
                <% end %>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary text-center">
                        <th>ID</th>
                        <th>Họ Tên</th>
                        <th>Email</th>
                        <th>Địa Chỉ</th>
                        <th>Phone</th>
                        <th>Cấp Bậc</th>
                        <th>Chức Năng</th>
                      </thead>
                      <% @admin_users.each do |admin_user| %>
                      <tbody>
                        <tr class="text-center">
                          <td><%= admin_user.id%></td>
                          <td><%= admin_user.name%></td>
                          <td><%= admin_user.email%></td>
                          <td><%= admin_user.address%></td>
                           <td><%= admin_user.phone_number%></td>
                          <% if admin_user.admin? %>
                            <td> Admin </td>
                          <% elsif admin_user.role == "staff" %>
                              <td> Nhan vien </td>
                              <% else %>
                              <td> khach hang </td>
                          <% end %>
                          <td>
                              <%= link_to "Sửa", edit_admin_user_path(admin_user) %>
                              <%= image_tag("edit.png", class: 'image_edit_delete') %>
                             <% if current_user.admin? %>
                                <%= link_to admin_user_path(admin_user), method: :delete,data: { confirm: "You sure?" } do %>
                                    Delete
                                    <%= image_tag("delete.png", class: 'image_edit_delete') %>
                                <% end %>
                              <% end %>
                          </td>
                        </tr>                                                                          
                      </tbody>
                      <% end %>
                    </table>
                    <%= will_paginate @admin_users %>
                  </div>
                </div>
              </div>
              
            </div>
    </div>
  </div>

app/views/admin/users/new.html.erb
<% provide(:title, "Thêm Mới Người Dùng")%>
<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Thêm Người Dùng</h4>
                </div>
                <div class="card-body">
                  <%= form_for [:admin, @admin_user] do |f| %>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <%= f.label :name, class: 'bmd-label-floating'%>
                          <%= f.text_field :name, class: 'form-control' %>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <%= f.label :email, class: 'bmd-label-floating'%>
                          <%= f.email_field :email, class: 'form-control' %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label :password, class: 'bmd-label-floating' %>
                          <%= f.password_field :password, class: 'form-control'%>
                        </div>
                      </div>
                    </div>
                     <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label :password_confirmation, class: 'bmd-label-floating' %>
                          <%= f.password_field :password_confirmation, class: 'form-control' %>
                        </div>
                      </div>
                    </div> 
                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                          <%= f.label :address, class: 'bmd-label-floating'%>
                          <%= f.text_field :address, class: 'form-control' %>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                            <%= f.label :phone_number, class: 'bmd-label-floating'%>
                          <%= f.number_field :phone_number, class: 'form-control' %>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Cấp Bậc</label>
                           <select class="form-control" >
                              <option>Admin</option>
                              <option>Nhân Viên</option>
                            </select>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-5"></div>
                      <div class="col-md-4">
                          <%= f.submit "Thêm Mới", class: "btn btn-primary text-center",data: { confirm: "ban muon them nguoi dung" } %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
</div>   